var express = require('express');
var app = express();
var bodyParser = require('body-parser')

const webPush = require('web-push');


// generated by using 
// console.log(webPush.generateVAPIDKeys()); return; 
var vapidKeys = {
    'privateKey': 'fwpvf7GqPOwHlBhXI0vgEikQxUbRpZGtXFrS84Losno',
    'publicKey': 'BAxsqBoOvwZjcoFmdMybEr2MgwsyBkRMEWjylFB8XnhNeCuxPBWNe8XpY-KlhB0G2pheUz7mzJswz6riSr59X-Q'
};

webPush.setVapidDetails(
    'http://localhost:3000/',
    vapidKeys.publicKey,
    vapidKeys.privateKey
  );

var subscriptions = {};

app.use(express.static('.'));

app.use(bodyParser.json());
// app.get('/vapidPublicKey', (req, res) => res.send(vapidKeys.publicKey));

app.post('/register', function(req, res) {
  console.log('register...');
  var subscription = req.body;
  if (!subscriptions[subscription.endpoint]) {
    console.log('  Subscription registered ' + subscription.endpoint);
    subscriptions[subscription.endpoint] = subscription;
  }

  res.json({}).status(201);
});

app.post('/sendNotification', function(req, res) {
  var msg = req.param("message", "hello from the server")
  console.log('send notification', msg);
  setTimeout(function() {
      webPush.sendNotification(subscriptions[req.body.endpoint], msg,  {"TTL": 60})
        .then(function() {
          res.sendStatus(201);
        })
        .catch(function(error) {
          console.error(error);
          res.sendStatus(500);
        });
    }, 1000);
  });

app.listen(3000, function () {
    console.log('Static webserver ready for action on port 3000!');
});